version: '3'
services:
  api:
    image: pferre/emaily
    build: .
    networks:
      - testing
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app
networks:
  testing:
    driver: bridge
